service: rimba-member-manager

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    USERS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-users
    DONATIONS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-donations
    
functions:
  create:
    handler: lambda/users/create
    events:
      - http:
          path: lambda/users
          method: post
          cors: true

  list:
    handler: lambda/users/list
    events:
      - http:
          path: lambda/users
          method: get
          cors: true

  get:
    handler: lambda/users/get
    events:
      - http:
          path: lambda/users/{id}
          method: get
          cors: true

  update:
    handler: lambda/users/update
    events:
      - http:
          path: lambda/users/{id}
          method: put
          cors: true

  delete:
    handler: lambda/users/delete
    events:
      - http:
          path: lambda/users/{id}
          method: delete
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DontationsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DONATIONS_TABLE}
        AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: N
        KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
